# Generated by Django 3.2.9 on 2022-01-04 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=89, unique=True, verbose_name='Property Type')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.administrator')),
            ],
            options={
                'verbose_name_plural': 'Property Type',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_title', models.CharField(max_length=90, verbose_name='Property title')),
                ('status', models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale')], max_length=20, verbose_name='Property status')),
                ('price', models.FloatField(default=0.0, verbose_name='price')),
                ('rooms', models.PositiveIntegerField(default=1, verbose_name='rooms')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='bathrooms')),
                ('balcony', models.PositiveIntegerField(blank=True, null=True, verbose_name='balcony')),
                ('bed_rooms', models.PositiveIntegerField(default=1, verbose_name='bedrooms')),
                ('garage', models.PositiveIntegerField(blank=True, null=True, verbose_name='garage')),
                ('area', models.CharField(help_text='SqFt', max_length=18, verbose_name='Area')),
                ('property_gallery', models.ImageField(upload_to='property/', verbose_name='property gallery')),
                ('rented', models.BooleanField(default=False, verbose_name='rented')),
                ('sold', models.BooleanField(default=False, verbose_name='sold')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('address', models.CharField(max_length=56, verbose_name='address')),
                ('city', models.CharField(max_length=57, verbose_name='City/Town')),
                ('postal_code', models.CharField(max_length=15, verbose_name='Postal code')),
                ('longitude', models.FloatField(default=31.67, verbose_name='longitude')),
                ('latitude', models.FloatField(default=0.0, verbose_name='latitude')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Detailed Information')),
                ('building_age', models.CharField(choices=[('0-1 Years', '0-1 Years'), ('2-5 Years', '2-5 Years'), ('6-10 Years', '6-10 Years'), ('11-15 Years', '11-15 Years'), ('16+ Years', '16+ Years')], max_length=56, verbose_name='Building age')),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='building plan', verbose_name='floor plan')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('parking', models.BooleanField(default=False, verbose_name='parking')),
                ('air_conditioning', models.BooleanField(default=False, verbose_name='air Condition')),
                ('swimming_pool', models.BooleanField(default=False, verbose_name='swimming pool')),
                ('laundry_room', models.BooleanField(default=False, verbose_name='laundry room')),
                ('window_covering', models.BooleanField(default=False, verbose_name='window covering')),
                ('central_heating', models.BooleanField(default=False, verbose_name='central heating')),
                ('alarm', models.BooleanField(default=False, verbose_name='alarm')),
                ('wifi', models.BooleanField(default=False, verbose_name='wifi')),
                ('gym', models.BooleanField(default=False, verbose_name='gym')),
                ('dining_room', models.BooleanField(default=False, verbose_name='dining_room')),
                ('list', models.BooleanField(default=False, verbose_name='list')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.seller')),
                ('like', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='Listings.property_type')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['featured', 'created_at'],
            },
        ),
    ]
