# Generated by Django 3.2.9 on 2022-01-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0002_property_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['featured', 'created_at'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='list',
            field=models.BooleanField(default=False, verbose_name='list'),
        ),
    ]
