# Generated by Django 3.2.9 on 2022-01-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Administrator', 'Administrator')], max_length=17, verbose_name='Role'),
        ),
    ]
