# Generated by Django 3.2.9 on 2021-12-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211229_1140'),
        ('Properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_type',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.administrator'),
        ),
    ]
