# Generated by Django 3.2.9 on 2021-12-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0002_alter_property_type_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(help_text='SqFt', max_length=18, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_age',
            field=models.CharField(choices=[('0-1 Years', '0-1 Years'), ('2-5 Years', '2-5 Years'), ('6-10 Years', '6-10 Years'), ('11-15 Years', '11-15 Years'), ('16+ Years', '16+ Years')], max_length=56, verbose_name='Building age'),
        ),
    ]
