# Generated by Django 3.2.9 on 2021-12-29 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Properties', '0003_auto_20211229_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
