# Generated by Django 3.2.9 on 2021-12-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0004_alter_property_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='Bed_rooms',
        ),
        migrations.AddField(
            model_name='property',
            name='bed_rooms',
            field=models.PositiveIntegerField(default=1, verbose_name='bedrooms'),
        ),
    ]
