# Generated by Django 3.2.9 on 2021-12-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0005_auto_20211229_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='air_conditioning',
            field=models.BooleanField(default=False, verbose_name='air Condition'),
        ),
    ]
