# Generated by Django 2.2.8 on 2019-12-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191226_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='contact_email',
            field=models.EmailField(default='daylightproperties@gmail.com', max_length=150),
        ),
        migrations.AddField(
            model_name='house',
            name='contact_phone',
            field=models.IntegerField(default='+254700215645'),
        ),
    ]
