# Generated by Django 2.2.8 on 2019-12-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191226_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.CharField(default='Day Light Properties Limited', max_length=30),
        ),
    ]
