# Generated by Django 2.2.8 on 2019-12-27 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_auto_20191226_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
