# Generated by Django 2.2.8 on 2019-12-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_house_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='display_image1',
            field=models.ImageField(blank=True, null=True, upload_to='display'),
        ),
        migrations.AddField(
            model_name='house',
            name='display_image2',
            field=models.ImageField(blank=True, null=True, upload_to='display'),
        ),
        migrations.AddField(
            model_name='house',
            name='display_image3',
            field=models.ImageField(blank=True, null=True, upload_to='display'),
        ),
    ]
