# Generated by Django 2.2.8 on 2019-12-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20191227_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='display_image4',
            field=models.ImageField(blank=True, null=True, upload_to='display'),
        ),
    ]
